### ISSUE TITLE
Trip Options Page

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#110]
Rectifying current duplication issue

**Comment by IshaDakota** [comment]
This is updated. Please note two steps you need to take to make trip option pages live:

1. There is a new field called "Descriptive Title" - this is the title for the individual pages and with no entry here, the title will be blank. This was created because the current titles fill the Tabs which necessarily need to be short. For example AMHSI could be "Alexander Muss High School ..." which is more descriptive.

2. Under Menu Settings, check the box for "Provide a menu link," set the title as desired, and make the "parent item" = "---- Trip Options"  This will ensure that the page gets properly placed in the sitemap.

@Shorashim Close this issue when you have read this and see it works properly.

**Comment by Shorashim** [comment]
It shouldn't show up on the main trip options page though, as it is. Correct?

![screen shot 2015-11-02 at 2 36 22 pm](https://cloud.githubusercontent.com/assets/13404688/10893591/52b75168-816f-11e5-849f-6834e31e0d32.png)

**Comment by IshaDakota** [comment]
No, you're right. it should not.

**Comment by Shorashim** [comment]
Please let me know when it is fixed and I will upload the rest of them. Thank you!

**Comment by IshaDakota** [comment]
it's fixed.
