### ISSUE TITLE
Tell Your Friends Form

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#138]
Should be same design as Pay It Forward, but a new form that links to separate results. Once it's live, I can edit the intro text.

**Comment by IshaDakota** [comment]
Because these are different pages, these are easy(ish) to do yourself.

First you need to create a new webform:

1. Go to Content -> Add Content -> Webform

2. Create the new "Tell you friends webform in any way that you like (you can use the existing "pay it forward" webform as a model to create the new one.

3. Save the webform adding any of the settings that you want (emails to send, etc).

After you have created the webform, we can add it to the page - I'll show you how to do that next.

**Comment by Shorashim** [comment]
All set. Also, random question, but is it possible to set it so all the answers export in the same format? I want everything to be in this format:

Your Name
email@email.org
(XXX) XXX-XXXX

It's easier for consistency when we export it, so I figured I would check if there's a way for me to set that up on the back-end.

**Comment by IshaDakota** [comment]
Don't understand... do you mean for the phone number field?

**Comment by Shorashim** [comment]
For name, email, and phone number - I would like them all to be consistent. People type in answers differently and it makes the excel docs very messy and takes time to clean up manually. If there was a way to avoid this, it would be helpful.

**Comment by IshaDakota** [comment]
There is no way on these forms to enforce a standard phone number format.

The others are text fields, so I'm not sure what you mean by standard.

**Comment by Shorashim** [comment]
It's okay then. I meant that it would be consistent so the first and last name would always be capitalized, the email would be lower case, and the phone number would be the same style. I always need to edit all of them for mail merges and because I am OCD about stuff like this, and it takes a long time, so was just trying to make it easier.
