### ISSUE TITLE
Tell Your Friends- Text Update

### ISSUE THREAD

**Issue by Shorashim** [MarchingLizard/iwiorg#84]
How to edit the wording on "Tell Your Friends" to be different than Pay It Forward?

**Comment by IshaDakota** [comment]
It's a duplicate. If you want it to be a new page, we need to build a new page.

**Comment by Shorashim** [comment]
I thought the reasoning behind not linking to Pay It Forward was because the messaging should be different? I wanted to use the same form, but have the text say "Tell Your Friends" and then have it say something along the lines of "Bring your friends to Israel with you." Is that possible to do?

**Comment by IshaDakota** [comment]
Yes, but not for release today... this is again a whole new page.

What we had discussed was putting this page in two places in the menu, because I had suggested that jumping menu sections was distracting. The solution was to put the duplicate page in two paces in the menu.

We will discuss on out launch call, because anyway I think the Pay It Forward/Share the Gift/Ambassador stuff is confusing.

**Comment by Shorashim** [comment]
Thanks - that makes sense. Let's talk on the call.

**Comment by IshaDakota** [comment]
completed (needs to be committed to repository).
